### ISSUE TITLE
compiler error 

### ISSUE THREAD

**Issue by nathansisler** [keijiro/KvantWig#3]
I get this error when I try to build for different devices. Not sure if it's something I may have broken but hope you might have an idea
![wigerror2](https://user-images.githubusercontent.com/17938652/37554009-a5ce3e5a-298f-11e8-99cc-737bc4585556.JPG)
![wigerror](https://user-images.githubusercontent.com/17938652/37554012-afdc3afa-298f-11e8-9c96-30ee985fd368.JPG)

**Comment by keijiro** [comment]
Fixed in the latest commit. https://github.com/keijiro/KvantWig/commit/a955fe2d7e53103472e4b5f07850f099b1a32d49

**Comment by keijiro** [comment]
I'm closing this ticket now. Please feel free to reopen for further problems.
